IF OBJECT_ID(N'[ODS].[DBO].[lkp_adverse_events]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_adverse_events];
BEGIN
            -- create table statement
	CREATE TABLE [ODS].[DBO].[lkp_adverse_events](
		source_name VARCHAR(100) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
		target_name VARCHAR(100) NOT NULL,
		date_created DATE NOT NULL
	)
	-- insert table
	INSERT INTO [ODS].[DBO].[lkp_adverse_events](
				source_name,
				target_name,
				date_created
	)
	VALUES          
	('Abdominal discomfort/abdominal pain', 'Abdominal pain',GETDATE()),
	('ABDOMINAL DISTENTION', 'Abdominal pain',GETDATE()),
	('Abdominal pain', 'Abdominal pain',GETDATE()),
	('Abnormal dreams or nightmares (Frightening or unpl', 'Nightmares',GETDATE()),
	('Abnormal dreams or nightmares (Frightening or unpleasant dreams)', 'Nightmares',GETDATE()),
	('Anaemia', 'Anaemia',GETDATE()),
	('Anaemia/pancytopenia', 'Anaemia',GETDATE()),
	('Anxiety (nervousness, fear, apprehension, and worr', 'Anxiety/Depression',GETDATE()),
	('AZT', 'HAART',GETDATE()),
	('BAD DREAMS', 'Nightmares',GETDATE()),
	('BARDYCARDIA', 'BRADYCARDIA',GETDATE()),
	('BLISTERS IN THE MOUT', 'Other ADRs',GETDATE()),
	('Burning and tingling in limbs/ Paresthesia/painful neuropathy', 'PERIPHERAL NEUROPATHY',GETDATE()),
	('Burning sensation and tingling in limbs/ Paresthes', 'PERIPHERAL NEUROPATHY',GETDATE()),
	('CNS', 'CNS',GETDATE()),
	('CNS MANIFESTATION', 'CNS',GETDATE()),
	('CNS(Central Nervous System)', 'CNS',GETDATE()),
	('Confusion/abnormal thinking', 'Anxiety/Depression',GETDATE()),
	('CONSTITUTIONAL', 'Abdominal pain',GETDATE()),
	('Cough ', 'Other ADRs',GETDATE()),
	('D4T TOXICITY', 'HAART',GETDATE()),
	('DARKENING OF NAIL', 'Other ADRs',GETDATE()),
	('Depression/mood changes (frequently feeling very l', 'Anxiety/Depression',GETDATE()),
	('Depression/mood changes (frequently feeling very low)', 'Anxiety/Depression',GETDATE()),
	('DHYNAELOMARIA', 'Other ADRs',GETDATE()),
	('Diarrhea', 'Diarrhoea',GETDATE()),
	('Diarrhoea', 'Diarrhoea',GETDATE()),
	('Difficulty Breathing', 'Other ADRs',GETDATE()),
	('DIZZINESS', 'DIZZINESS',GETDATE()),
	('Dizziness/spinning sensation/vertigo', 'DIZZINESS',GETDATE()),
	('Drowsiness', 'DIZZINESS',GETDATE()),
	('ERYTHEMICRASH', 'Skin rash',GETDATE()),
	('EXCESSIVE VOMITING', 'Nausea/Vomit',GETDATE()),
	('Fat changes/lipodystrophy', 'LIPODYSTROPHY',GETDATE()),
	('Fat changes/lipodystrophy/lipohypertrophy', 'LIPODYSTROPHY' ,GETDATE()),
	('Fatigue/tiredness/weakness', 'LETHARGIC',GETDATE()),
	('Fever', 'Fever',GETDATE()),
	('FORMULATION', 'HAART',GETDATE()),
	('GASTRITIS', 'Diarrhoea',GETDATE()),
	('Generalised itchy skin rash', 'Skin rash',GETDATE()),
	('GIT INTORERANCE', 'Nausea/Vomit',GETDATE()),
	('Gynaecomastia', 'Gynecomastia',GETDATE()),
	('Gynecomastia', 'Gynecomastia',GETDATE()),
	('HAART (HAEMOLYSE ANA', 'HAART',GETDATE()),
	('HALLUCINATION', 'Anxiety/Depression',GETDATE()),
	('hallucinations', 'Anxiety/Depression',GETDATE()),
	('Headache', 'Headache',GETDATE()),
	('Hepatic Toxicity', 'Hepatic Toxicity',GETDATE()),
	('Hepatic Toxicity (LFT >5x normal)', 'Hepatic Toxicity',GETDATE()),
	('Hepatotoxicity', 'Hepatic Toxicity',GETDATE()),
	('Hepatoxicity', 'Hepatic Toxicity',GETDATE()),
	('Hyperglyceamia', 'Hyperglycemia',GETDATE()),
	('Hyperglycemia', 'Hyperglycemia',GETDATE()),
	('Hyperlipidemia', 'Hyperlipidemia',GETDATE()),
	('Hyperlipidimia', 'Hyperlipidemia',GETDATE()),
	('IMMUNOSUPPRESSION', 'Other ADRs',GETDATE()),
	('INH', 'Other ADRs',GETDATE()),
	('Insomnia', 'Insomnia',GETDATE()),
	('Insomnia (lacking sleep at night)/sleep problems', 'Insomnia',GETDATE()),
	('IRIS', 'Other ADRs',GETDATE()),
	('ITCHNESS', 'Skin rash',GETDATE()),
	('itchy skin and dark rash', 'Skin rash',GETDATE()),
	('Jaundice', 'Jaundice',GETDATE()),
	('Jaundice, dizziness', 'DIZZINESS',GETDATE()),
	('KS', 'Other ADRs',GETDATE()),
	('LACTIC ACIDIOSIS', 'LACTIC ACIDIOSIS',GETDATE()),
	('Lactic Acidosis', 'LACTIC ACIDIOSIS',GETDATE()),
	('LETHARGIC', 'LETHARGIC',GETDATE()),
	('LIPODYSTROPHY', 'LIPODYSTROPHY',GETDATE()),
	('Liver Failure', 'Liver Failure',GETDATE()),
	('LOW HB', 'LOW HB',GETDATE()),
	('LYMPHADENOPATHY', 'LYMPHADENOPATHY',GETDATE()),
	('LYPODYSTROPHY', 'LIPODYSTROPHY',GETDATE()),
	('MALAISE', 'Other ADRs',GETDATE()),
	('MITOCHONDRIAL', 'Other ADRs',GETDATE()),
	( 'MUSCLE WASTING', 'Weight Changes',GETDATE()),
	( 'Nausea', 'Nausea/Vomit',GETDATE()),
	( 'NAUSEA AND VOMITING', 'Nausea/Vomit',GETDATE()),
	( 'Nausea/vomiting', 'Nausea/Vomit',GETDATE()),
	( 'NAVEA', 'Other ADRs',GETDATE()),
	( 'NEOROLOGICAL', 'PERIPHERAL NEUROPATHY',GETDATE()),
	( 'Nephropathy', 'PERIPHERAL NEUROPATHY',GETDATE()),
	( 'NEPHROTOXICITY', 'PERIPHERAL NEUROPATHY',GETDATE()),
	( 'NUMBNESS', 'NUMBNESS',GETDATE()),
	( 'NUMBNESS ON THE CHEEK', 'NUMBNESS',GETDATE()),
	( 'Other ADRs', 'Other ADRs',GETDATE()),
	( 'Other Specify', 'Other ADRs',GETDATE()),
	( 'Other Specify PERIPHERAL NEUROPATHY', 'PERIPHERAL NEUROPATHY',GETDATE()),
	( 'P/Neuropathy', 'PERIPHERAL NEUROPATHY',GETDATE()),
	( 'Pancreatitis', 'Pancreatitis',GETDATE()),
	( 'Papular Pruritic Eruptions', 'Skin rash',GETDATE()),
	( 'Psychosis', 'Anxiety/Depression',GETDATE()),
	( 'rash', 'Skin rash',GETDATE()),
	( 'RASH GRADE 2', 'Skin rash',GETDATE()),
	( 'Renal failure/renal insufficiency', 'RENAL TOXICITY',GETDATE()),
	( 'RENAL TOXICITY', 'RENAL TOXICITY',GETDATE()),
	( 'SELIPODYSTROPHY', 'LIPODYSTROPHY',GETDATE()),
	( 'SJS', 'Stevens Johnson Syndrome',GETDATE()),
	( 'Skin rash', 'Skin rash',GETDATE()),
	( 'Skin rash/hypersensitivity reaction', 'Skin rash',GETDATE()),
	( 'STEVE JOHNSON SYNDRO', 'Stevens Johnson Syndrome',GETDATE()),
	( 'Stevens Johnson Syndrome', 'Stevens Johnson Syndrome',GETDATE()),
	( 'Suicide ideation (thoughts on ending the life)', 'Anxiety/Depression',GETDATE()),
	( 'Vomiting', 'Nausea/Vomit',GETDATE()),
	( 'Weight gain', 'Weight Changes',GETDATE()),
	( 'WEIGHT GAIN REPORTED ', 'Weight Changes',GETDATE()),
	( 'Weight loss', 'Weight Changes',GETDATE())

END