IF OBJECT_ID(N'[ODS].[DBO].[lkp_patient_source]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_patient_source];
BEGIN
		-- create table statement
		CREATE TABLE [ODS].[DBO].[lkp_patient_source](
			source_name VARCHAR(50) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
			target_name VARCHAR(50) NOT NULL,
			date_created DATE NOT NULL
		)

		-- insert to table statement
		INSERT INTO  [ODS].[DBO].[lkp_patient_source](
				   source_name,
				   target_name,
				   date_created
		)
		VALUES
		('VCT','VCT',GETDATE()),
		('OPD','OPD',GETDATE()),
		('PMTCT','MCH',GETDATE()),
		('CCC','CCC',GETDATE()),
		('TB','TB Clinic',GETDATE()),
		('IPD - Adult','IPD ',GETDATE()),
		('TRANSFER-IN','OPD',GETDATE()),
        ('In Patient Department(IPD)','IPD',GETDATE()),
        ('IPD-Adult','IPD',GETDATE()),
		('OUT PATIENT DEPARTMENT','OPD',GETDATE()),
		('PITC','OTHER',GETDATE()),
		('Maternal and child health program','MCH',GETDATE()),
        ('Community Health Care Provider','Community Testing',GETDATE()),
		('MCH-Chd','MCH',GETDATE()),
		('CCHC','OTHER',GETDATE()),
		('ANC/PPCT','MCH',GETDATE()),
		('IPD-Ad','IPD',GETDATE()),
		('OTHER NON CODED','OTHER',GETDATE()),
		('mch.cwc','MCH',GETDATE()),
		('NODREAM','OTHER',GETDATE()),
		('IPD-Chd','IPD',GETDATE()),
		('RESEARCH','OTHER',GETDATE()),
		('Inpatient Adult','IPD',GETDATE()),
		('MCPC_C','OTHER',GETDATE()),
		('7','PITC',GETDATE()),
		('Home based HIV testing program','HBTC',GETDATE()),
        ('Home Based Testing','HBTC',GETDATE()),
		('2','VCT',GETDATE()),
		('IN PATIENT DEPARTMENT - ADULT','IPD',GETDATE()),
		('MCPC','OTHER',GETDATE()),
		('PEP','OTHER',GETDATE()),
		('5','OTHER',GETDATE()),
		('Unknown','OTHER',GETDATE()),
		('OUTREACH','OTHER',GETDATE()),
		('8','CCC',GETDATE()),
		('HOME BASED COUNSELING AND TESTING (HBCT)','HBTC',GETDATE()),
		('VMMC','VMMC',GETDATE()),
		('IN PATIENT DEPARTMENT - CHILD','IPD',GETDATE()),
		('Inpatient Children','IPD',GETDATE()),
		('ENDASS','OTHER',GETDATE()),
		('PREP','OTHER',GETDATE()),
		('STI','OTHER',GETDATE()),
		('3','TB Clinic',GETDATE()),
		('1','MCH',GETDATE()),
		('CHCW','OTHER',GETDATE()),
		('LABOR WARD','OTHER',GETDATE()),
		('6','VMMC',GETDATE()),
		('SELF REFFERA','OTHER',GETDATE()),
		('OPD-Adult','OPD',GETDATE()),
        ('Out Patient Department(OPD)','OPD',GETDATE()),
		('4','CWC',GETDATE()),
		('ORPHANAGE','OTHER',GETDATE()),
		('TBCARE','TB Clinic',GETDATE()),
		('SELF REFERRAL','OTHER',GETDATE()),
        ('5485' ,'IPD',GETDATE()),
        ('160542' ,'OPD',GETDATE()),
        ('1965' ,'OPD',GETDATE()),
        ('162181' ,'Peadiatric Clinic',GETDATE()),
        ('2219' ,'Peadiatric Clinic',GETDATE()),
        ('10138' ,'Nutrition Clinic',GETDATE()),
        ('160552' ,'Nutrition Clinic',GETDATE()),
        ('Nutrition Clinicc' ,'Nutrition Clinic',GETDATE()),
        ('160538' ,'PMTCT ANC',GETDATE()),
        ('ANC' ,'PMTCT ANC',GETDATE()),
        ('160456' ,'PMTCT MAT',GETDATE()),
        ('1623' ,'PMTCT PNC',GETDATE()),
        ('1975' ,'PMTCT PNC',GETDATE()),
        ('160541','TB',GETDATE()),
        ('10649','TB',GETDATE()),
        ('162050','CCC',GETDATE()),
        ('159940','VCT',GETDATE()),
        ('2047','VCT',GETDATE()),
        ('159938','HBTC',GETDATE()),
        ('2049','HBTC',GETDATE()),
        ('159939','Mobile Outreach',GETDATE()),
        ('Sensitization Campaign','Mobile Outreach',GETDATE()),
        ('2048','Mobile Outreach',GETDATE()),
        ('162223','VMMC',GETDATE()),
        ('8707','VMMC',GETDATE()),
        ('160546','STI Clinic',GETDATE()),
        ('1964','STI Clinic',GETDATE()),
        ('160522','Emergency',GETDATE()),
        ('7974','Emergency',GETDATE()),
        ('163096','Community Testing',GETDATE()),
        ('163096','Community Testing',GETDATE()),
        ('1862','Community Testing',GETDATE()),
        ('1776','PMTCT',GETDATE()),
        ('9494','Maternity',GETDATE()),
        ('5622','Other',GETDATE()),
        ('56222','Other',GETDATE()),
        ('Other Facility Referral ','Other',GETDATE()),
        ('VCT WALK IN ','VCT',GETDATE()),
        ('161557','Index Testing',GETDATE()),
        ('IndexTesting','Index Testing',GETDATE()),
        ('INDEX TESTING','Index Testing',GETDATE()),
        ('Partner Testing','PNS',GETDATE()),
        ('','NULL',GETDATE()),
        ('NULL','NULL',GETDATE())
        
       
        End


   
         