IF OBJECT_ID(N'[ODS].[DBO].[lkp_family_planning_method]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_family_planning_method];
BEGIN
		-- create table statement
		CREATE TABLE [ODS].[DBO].[lkp_family_planning_method](
			source_name VARCHAR(250) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
			target_name VARCHAR(250) NOT NULL,
			date_created DATE NOT NULL
		)

		-- insert table
		INSERT INTO [ODS].[DBO].[lkp_family_planning_method] (
				   source_name,
				   target_name,
				   date_created
		)
		VALUES
		('Not using FP','Not using FP',GETDATE()),
		('CONDOMS','Condoms',GETDATE()),
		(' Condoms','Condoms',GETDATE()),
		('MEDROXYPROGESTERONE ACETATE','Injectable Contraceptive',GETDATE()),
		('Wants FP','Wants FP',GETDATE()),
		('INJECTABLE (INJ)','Injectable Contraceptive',GETDATE()),
		('IMPLANON(IMP)','Implant',GETDATE()),
		('CONTRACEPTIVE IMPLANT','Implant',GETDATE()),
		(' Injectable','Injectable Contraceptive,Implant',GETDATE()),
		('NONE','Not using FP',GETDATE()),
		('C =condoms','Condoms',GETDATE()),
		('INJECTABLE CONTRACEPTIVES','Injectable Contraceptive',GETDATE()),
		('5-YEAR CONTRACEPTIVE IMPLANT','Implant',GETDATE()),
		('3-YEAR CONTRACEPTIVE IMPLANT','Implant',GETDATE()),
		(' Implant','Implant',GETDATE()),
		('INTRAUTERINE DEVICE','Intrauterine Contraceptive Device',GETDATE()),
		('FEMALE STERILIZATION','Tubal Ligation',GETDATE()),
		(' Condoms; Injectable','Condoms,Injectable Contraceptive',GETDATE()),
		('INJ =Injectable','Injectable Contraceptive',GETDATE()),
		('ORAL CONTRACEPTION','Oral Contraceptives Pill',GETDATE()),
		('OC','Oral Contraceptives Pill',GETDATE()),
		('MALE CONDOMS',' Male Condoms',GETDATE()),
		('COPPER INTRAUTERINE DEVICE','Non-Hormonal Intrauterine Contraceptive Device',GETDATE()),
		(' Oral Contraceptive Pills','Oral Contraceptives Pill',GETDATE()),
		('IMP =implant','Implant',GETDATE()),
		('TL','Tubal Ligation',GETDATE()),
		('COMBINED HORMONE ORAL CONTRACEPTIVE PILL','Condoms',GETDATE()),
		('IUD','Intrauterine Contraceptive Device',GETDATE()),
		('LAM','Lactational Amenorrhea Method',GETDATE()),
		(' Condoms; Implant','Condoms,Implant',GETDATE()),
		(' Tubal Ligation','Tubal Ligation',GETDATE()),
		('TUBAL LIGATION','Tubal Ligation',GETDATE()),
		('ABSTINENCE','Abstinence',GETDATE()),
		(' IUD =intrauterine device','Intrauterine Contraceptive Device',GETDATE()),
		('PROGESTIN PILLS','Oral Contraceptive',GETDATE()),
		('HORMONAL INTRAUTERINE DEVICE','Hormonal Intrauterine Contraceptive Device',GETDATE()),
		(' Intra Uterine Device','Intrauterine Contraceptive Device',GETDATE()),
		(' Condoms; Oral Contraceptive Pills','Condoms, Oral Contraceptive Pill',GETDATE()),
		('Injectable','Injectable Contraceptive',GETDATE()),
		('NATURAL FAMILY PLANNING','Natural Family Planning',GETDATE()),
		('OC =oral contraceptive pills','Oral Contraceptives Pill',GETDATE()),
		('Lactational Amenorrhea Method','Lactational Amenorrhea Method',GETDATE()),
		(' Condoms; Condoms','Condoms',GETDATE()),
		('FA','Fertility Awareness Method',GETDATE()),
		('IUD =intrauterine device','Intrauterine Contraceptive Device',GETDATE()),
		('TL =tubal ligation/female sterilization','Tubal Ligation',GETDATE()),
		('DIAPHRAGM','Diaphragm',GETDATE()),
		('JADELLE(IMP)','Injectable Contraceptive',GETDATE()),
		('NORPLANT (IMPLANTABLE CONTRACEPTIVE','Implant',GETDATE()),
		('Implant','Implant',GETDATE()),
		('FEMALE CONDOMS','Female Condoms',GETDATE()),
		(' LAM =Lactational Amenorrhea Method','Lactational Amenorrhea Method',GETDATE()),
		(' Condoms; IUD =intrauterine device','Condoms, Intrauterine Contraceptive Device',GETDATE()),
		('NORPLANT','Implant',GETDATE()),
		(' ECP =emergency contraceptive pills dispensed','Emergency Contraceptive Pills',GETDATE()),
		(' D =diaphragm/cervical cap','Diaphragm',GETDATE()),
		(' Tubal Ligation; Condoms','Tubal Ligation',GETDATE()),
		('MEDROXYPROGESTERONE ACETATE(DEPO)','Injectable Contraceptive',GETDATE()),
		(' Injectable; Injectable','Injectable Contraceptive',GETDATE()),
		('LAM =Lactational Amenorrhea Method','Lactational Amenorrhea Method',GETDATE()),
		(' Implant; Implant','Implant',GETDATE()),
		('EMERGENCY CONTRACEPTIVE PILLS','Emergency Contraceptive Pill',GETDATE()),
		('CONTRACEPTION METHOD UNDECIDED','Undecided',GETDATE()),
		('Tubal Ligation /Female Sterilization','Tubal Ligation',GETDATE()),
		('ECP','Emergency Contraceptive Pill',GETDATE()),
		(' Injectable; Implant','Injectable Contraceptive',GETDATE()),
		('Intra Uterine Device','Intrauterine Contraceptive Device',GETDATE()),
		(' periodic abstinence','Abstinence',GETDATE()),
		(' Emergency Contraceptive Pills','Emergency Contraceptive Pill',GETDATE()),
		(' Lactational Amenorrhea Method','Lactational Amenorrhea Method',GETDATE()),
		('FA =fertility awareness method/periodic abstinence','Fertility Awareness Method',GETDATE()),
		('VASECTOMY','Vasectomy',GETDATE()),
		(' Condoms; ECP =emergency contraceptive pills dispensed','Condoms,Emergency Contraceptive Pill',GETDATE()),
		(' Condoms; Intra Uterine Device','Condoms,Injectable Contraceptive, Intrauterine Contraceptive Device',GETDATE()),
		('OTHER NON-CODED','Other non-coded',GETDATE()),
		(' Fertility Awareness Method','Fertility Awareness Method',GETDATE()),
		('ECP =emergency contraceptive pills dispensed','Emergency Contraceptive Pill',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Condoms','Lactational Amenorrhea Method,Condoms',GETDATE()),
		(' UND =undecided','Not using FP',GETDATE()),
		(' Diaphragm/Cervical Cap','Diaphragm',GETDATE()),
		(' Condoms; Tubal Ligation','Condoms, Tubual Ligation',GETDATE()),
		(' Oral Contraceptive Pills; Injectable','Oral Contraceptives Pill',GETDATE()),
		('HERBAL TRADITIONAL MEDICATIONS','Herbal Traditional Medications',GETDATE()),
		(' Condoms; Condoms; Injectable; Injectable','Condoms,Injectable Contraceptives',GETDATE()),
		(' Intra Uterine Device; Intra Uterine Device','Intrauterine Contraceptive Device',GETDATE()),
		('VASECTOMY(V)','Vasectomy',GETDATE()),
		(' Oral Contraceptive Pills; Oral Contraceptive Pills','Oral Contraceptives Pill',GETDATE()),
		('Oral Contraceptive Pills','Oral Contraceptives Pill',GETDATE()),
		(' Condoms; Condoms; Condoms','Condoms',GETDATE()),
		('INJ','Injectable Contraceptive',GETDATE()),
		(' Condoms; Condoms; Implant; Implant','Condoms,Implant',GETDATE()),
		(' Condoms; Oral Contraceptive Pills; Injectable','Condoms, Oral Contraceptive Pill, Injectable Contraceptives',GETDATE()),
		('D =diaphragm/cervical cap','Diaphragm',GETDATE()),
		(' Condoms; Injectable; Implant','Condoms,Injectable Contraceptive',GETDATE()),
		(' periodic abstinence; Condoms','Condoms',GETDATE()),
		(' Condoms; Condoms; Condoms; Condoms','Condoms',GETDATE()),
		(' Tubal Ligation; Tubal Ligation','Tubal Ligation',GETDATE()),
		(' IUD =intrauterine device; Intra Uterine Device','Intrauterine Contraceptive Device',GETDATE()),
		(' Condoms; Emergency Contraceptive Pills','Condoms,Emergency Contraceptive Pill',GETDATE()),
		(' Implant; Condoms; Oral Contraceptive Pills','Implant, Condoms,Oral Contraceptive Pill',GETDATE()),
		('C','Condoms',GETDATE()),
		(' D =diaphragm/cervical cap; Condoms','Diaphragm, Condoms',GETDATE()),
		('UND =undecided','Undecided',GETDATE()),
		(' Injectable; Injectable; Injectable','Injectable Contraceptive',GETDATE()),
		(' Implant; Implant; Implant','Implant',GETDATE()),
		(' Emergency Contraceptive Pills; Oral Contraceptive Pills','Emergency Contraceptive Pill,Oral Contraceptive Pill',GETDATE()),
		(' ECP =emergency contraceptive pills dispensed; Oral Contraceptive Pills','Emergency Contraceptive Pill, Oral Contraceptive Pill',GETDATE()),
		(' Vasectomy','Vasectomy',GETDATE()),
		(' Condoms; Lactational Amenorrhea Method','Condoms, Lactational Amenorrhea Method',GETDATE()),
		(' Vasectomy; Oral Contraceptive Pills','Vasectomy',GETDATE()),
		(' Condoms; Condoms; Injectable','Condoms,Injectable Contraceptives',GETDATE()),
		(' Vasectomy; Condoms','Vasectomy',GETDATE()),
		(' Oral Contraceptive Pills; Implant','Oral Contraceptives Pill',GETDATE()),
		(' ECP =emergency contraceptive pills dispensed; Injectable','Emergency Contraceptive Pill, Injectable Contraceptive',GETDATE()),
		(' Tubal Ligation; Injectable','Tubal Ligation',GETDATE()),
		(' Injectable; Injectable; Injectable; Injectable','Injectable Contraceptive',GETDATE()),
		(' Condoms; Injectable; Injectable','Condoms,Injectable Contraceptive,Implant',GETDATE()),
		(' Condoms; Implant; Implant','Condoms,Implant',GETDATE()),
		(' Condoms; ECP =emergency contraceptive pills dispensed; Oral Contraceptive Pills','Condoms,Emergency Contraceptive Pill,Oral Contraceptive Pill',GETDATE()),
		(' Condoms; Condoms; Oral Contraceptive Pills; Oral Contraceptive Pills','Condoms, Oral Contraceptive Pill',GETDATE()),
		(' Condoms; Condoms; Implant','Condoms,Implant',GETDATE()),
		(' Condoms; Condoms; Condoms; Condoms; Condoms','Condoms',GETDATE()),
		('D','Diaphragm',GETDATE()),
		(' Oral Contraceptive Pills; Oral Contraceptive Pills; Oral Contraceptive Pills','Oral Contraceptives Pill',GETDATE()),
		(' D =diaphragm/cervical cap; Injectable','Diaphragm, Injectable Contraceptive',GETDATE()),
		(' Condoms; ECP =emergency contraceptive pills dispensed; Oral Contraceptive Pills; Injectable','Condoms,Emergency Contraceptive Pills,Oral Contraceptive Pill,Injectable Contraceptive',GETDATE()),
		('INJ, C','Injectable Contraceptive',GETDATE()),
		(' Tubal Ligation; Oral Contraceptive Pills','Tubal Ligation',GETDATE()),
		(' Intra Uterine Device; Intra Uterine Device; Intra Uterine Device','Intrauterine Contraceptive Device',GETDATE()),
		(' Injectable; IUD =intrauterine device','Injectable Contraceptive,Intrauterine Contraceptive Device',GETDATE()),
		(' Injectable; Intra Uterine Device','Injectable Contraceptive,Intrauterine Contraceptive Device',GETDATE()),
		(' Injectable; Injectable; Implant','Injectable Contraceptive,Implant',GETDATE()),
		(' Emergency Contraceptive Pills; Implant','Emergency Contraceptive Pill, Implant',GETDATE()),
		(' Emergency Contraceptive Pills; Emergency Contraceptive Pills','Emergency Contraceptive Pill',GETDATE()),
		('O','Oral Contraceptives Pill',GETDATE()),
		(' UND =undecided; Implant','Implant',GETDATE()),
		(' UND =undecided; Condoms','Condoms',GETDATE()),
		(' Tubal Ligation; ECP =emergency contraceptive pills dispensed','Tubal Ligation',GETDATE()),
		(' Oral Contraceptive Pills; IUD =intrauterine device','Oral Contraceptives Pill',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Oral Contraceptive Pills','Lactational Amenorrhea Method,Oral Contraceptive Pill',GETDATE()),
		(' Lactational Amenorrhea Method; Tubal Ligation','Tubal Ligation',GETDATE()),
		(' Lactational Amenorrhea Method; Lactational Amenorrhea Method','Lactational Amenorrhea Method',GETDATE()),
		(' Intra Uterine Device; Diaphragm/Cervical Cap; Diaphragm/Cervical Cap','Diaphragm',GETDATE()),
		(' Implant; Tubal Ligation','Implant, Tubal Ligation',GETDATE()),
		(' Implant; IUD =intrauterine device','Implant, Intrauterine Contraceptive Device',GETDATE()),
		(' Implant; Intra Uterine Device','Implant,Intrauterine Contraceptive Device',GETDATE()),
		(' Emergency Contraceptive Pills; Injectable','Emergency Contraceptive Pill,Injectable Contraceptive',GETDATE()),
		(' D =diaphragm/cervical cap; ECP =emergency contraceptive pills dispensed','Diaphragm, Emergency Contraceptive Pill',GETDATE()),
		(' Condoms; Oral Contraceptive Pills; Oral Contraceptive Pills','Condoms, Oral Contraceptive Pill',GETDATE()),
		(' Condoms; Oral Contraceptive Pills; Implant','Condoms, Oral Contraceptive Pill, Implant',GETDATE()),
		(' Condoms; Condoms; Oral Contraceptive Pills; Injectable; Injectable','Condoms, Oral Contraceptive Pill, Injectable Contraceptives',GETDATE()),
		('IMP','Implant',GETDATE()),
		('Fertility Awareness Method','Fertility Awareness Method',GETDATE()),
		('D, C','Diaphragm',GETDATE()),
		(' UND =undecided; Injectable','Injectable Contraceptive',GETDATE()),
		(' Tubal Ligation; Tubal Ligation; Tubal Ligation','Tubal Ligation',GETDATE()),
		(' Tubal Ligation; IUD =intrauterine device','Tubal Ligation',GETDATE()),
		(' Tubal Ligation; Implant','Tubal Ligation',GETDATE()),
		(' Tubal Ligation; Condoms; Injectable','Tubal Ligation',GETDATE()),
		(' periodic abstinence; Implant','Implant',GETDATE()),
		(' periodic abstinence; Condoms; Implant','Implant',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Injectable','Lactational Amenorrhea Method, Injectable Contraception',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Implant','Lactational Amenorrhea Method,Implant',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Condoms; Oral Contraceptive Pills','Lactational Amenorrhea Method,Oral Contraceptive Pill',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Condoms; Injectable','Lactational Amenorrhea Method,Injectable Contraception',GETDATE()),
		(' LAM =Lactational Amenorrhea Method; Condoms; Implant','Lactational Amenorrhea Method,Implant',GETDATE()),
		(' Intra Uterine Device; Tubal Ligation','Tubal Ligation',GETDATE()),
		(' Injectable; Implant; IUD =intrauterine device','Injectable ,Intrauterine Contraceptive Device',GETDATE()),
		(' Fertility Awareness Method; Fertility Awareness Method','Fertility Awareness Method',GETDATE()),
		(' Emergency Contraceptive Pills; Emergency Contraceptive Pills; Oral Contraceptive Pills; Oral Contraceptive Pills','Emergency Contraceptive Pill, Oral Contraceptive Pill',GETDATE()),
		(' D =diaphragm/cervical cap; Implant','Diaphragm, Emergency Contraceptive Pill',GETDATE()),
		(' Condoms; Injectable; IUD =intrauterine device','Condoms,Injectable Contraceptive',GETDATE()),
		(' Condoms; Implant; Tubal Ligation','Condoms, Implant,Tubal Ligation',GETDATE()),
		(' Condoms; Implant; IUD =intrauterine device','Condoms,Implant, Intrauterine Contraceptive Device',GETDATE()),
		(' Condoms; ECP =emergency contraceptive pills dispensed; Implant','Condoms,Emergency Contraceptive Pill,Oral Contraceptive Pill,Implant',GETDATE()),
		(' Condoms; Condoms; Tubal Ligation; Tubal Ligation','Condoms, Tubal Ligation',GETDATE()),
		(' Condoms; Condoms; Tubal Ligation','Condoms, Tubal Ligation',GETDATE()),
		(' Condoms; Condoms; Intra Uterine Device','Condoms,Intrauterine Contraceptive Device',GETDATE()),
		(' Condoms; Condoms; Condoms; Injectable; Injectable; Injectable','Condoms,Injectable Contraceptives',GETDATE()),
		(' Condoms; Condoms; Condoms; Implant; Implant; Implant','Condoms,Implant',GETDATE())

END