IF OBJECT_ID(N'[ODS].[DBO].[lkp_allergic_reaction]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_allergic_reaction];
BEGIN
		-- create table statement
		CREATE TABLE [ODS].[DBO].[lkp_allergic_reaction](
			source_name VARCHAR(50) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
			target_name VARCHAR(50) NOT NULL,
			date_created DATE NOT NULL
		)
		-- insert table
		INSERT INTO [ODS].[DBO].[lkp_allergic_reaction](
				   source_name,
				   target_name,
				   date_created
		)
		VALUES
		('abicavir','OTHER',GETDATE()),
		('allergic to red meat and eggs','OTHER',GETDATE()),
		('allergic to septrin','OTHER',GETDATE()),
		('allergic to sulphur','OTHER',GETDATE()),
		('allergic to sulphur drugs','OTHER',GETDATE()),
		('Anaemia','Anaemia',GETDATE()),
		('Anaemia|Hypertension','Anaemia',GETDATE()),
		('Angioedema','Angioedema',GETDATE()),
		('Angioedema|Angioedema','Angioedema',GETDATE()),
		('animal protiens','OTHER',GETDATE()),
		('Arrhythmia','Arrhythmia',GETDATE()),
		('Arrhythmia|Arrhythmia','Arrhythmia',GETDATE()),
		('aspirin based drugs','OTHER',GETDATE()),
		('ASTHMA','Asthma',GETDATE()),
		('asthmatic','Asthma',GETDATE()),
		('beans','OTHER',GETDATE()),
		('BURNS','OTHER',GETDATE()),
		('cold','OTHER',GETDATE()),
		('COLD ALLERGY','OTHER',GETDATE()),
		('cold and dust','OTHER',GETDATE()),
		('cold weather','OTHER',GETDATE()),
		('Cough','Cough',GETDATE()),
		('Cough|Cough','Cough',GETDATE()),
		('ctx','OTHER',GETDATE()),
		('ctx allegry','OTHER',GETDATE()),
		('Diarrhea','Diarrhea',GETDATE()),
		('Diarrhea|Cough','Diarrhea',GETDATE()),
		('dust','Dust',GETDATE()),
		('dust and cold','Dust',GETDATE()),
		('dust, cold and perfume','Dust',GETDATE()),
		('Dystonia','Dystonia',GETDATE()),
		('eggs','OTHER',GETDATE()),
		('eggs and fatty foods','OTHER',GETDATE()),
		('EGGS AND MEAT','OTHER',GETDATE()),
		('fish and pork','OTHER',GETDATE()),
		('Flushing','Flushing',GETDATE()),
		('GI upset','GI upset',GETDATE()),
		('GOAT AND NILE PERCH','OTHER',GETDATE()),
		('goat meat','OTHER',GETDATE()),
		('GOATMEAT','OTHER',GETDATE()),
		('Headache','Headache',GETDATE()),
		('Headache|Headache','Headache',GETDATE()),
		('Headache|Hepatotoxicity|Headache','Headache',GETDATE()),
		('Hepatotoxicity','Hepatotoxicity',GETDATE()),
		('high protein','OTHER',GETDATE()),
		('high protein diet','OTHER',GETDATE()),
		('high protein diet, especially eggs','OTHER',GETDATE()),
		('Hives','Hives',GETDATE()),
		('hypersensitivity','OTHER',GETDATE()),
		('Hypertension','Hypertension',GETDATE()),
		('itchiness','Itching',GETDATE()),
		('Itching','Itching',GETDATE()),
		('meat','OTHER',GETDATE()),
		('meat red meat','OTHER',GETDATE()),
		('Mental status change','Mental status change',GETDATE()),
		('Mental status change|Mental status change','Mental status change',GETDATE()),
		('Musculoskeletal pain','Musculoskeletal Pain',GETDATE()),
		('MUTTON,FISH','OTHER',GETDATE()),
		('Myalgia','Myalgia',GETDATE()),
		('NEVIRAPINE','OTHER',GETDATE()),
		('none','OTHER',GETDATE()),
		('NULL','OTHER',GETDATE()),
		('oduors','OTHER',GETDATE()),
		('Other','OTHER',GETDATE()),
		('Other|Other','OTHER',GETDATE()),
		('paracetamol','OTHER',GETDATE()),
		('Penicillin','OTHER',GETDATE()),
		('PENINCILLINS / SULPHUR','OTHER',GETDATE()),
		('PERFUMES AND DUST','OTHER',GETDATE()),
		('PERIORBITAL OEDEMA AND ITCHYNESS ON WHOLE BODY','Itching',GETDATE()),
		('PROTEIN','OTHER',GETDATE()),
		('proteins','OTHER',GETDATE()),
		('QUINOLONES','OTHER',GETDATE()),
		('Rash','Rash',GETDATE()),
		('RASH AND SORES','Rash',GETDATE()),
		('rashes','Rash',GETDATE()),
		('reaction','OTHER',GETDATE()),
		('red meat','OTHER',GETDATE()),
		('Red meat and cold','OTHER',GETDATE()),
		('SEPRINE','OTHER',GETDATE()),
		('septrin','OTHER',GETDATE()),
		('septrium','OTHER',GETDATE()),
		('severe','OTHER',GETDATE()),
		('sjs','OTHER',GETDATE()),
		('skin  allergies','Rash',GETDATE()),
		('skin  rash','Rash',GETDATE()),
		('skin rash','Rash',GETDATE()),
		('skin reaction','Rash',GETDATE()),
		('sulphar','OTHER',GETDATE()),
		('SULPHUR','OTHER',GETDATE()),
		('Sulphur Allergy','OTHER',GETDATE()),
		('sulphur and penicillin','OTHER',GETDATE()),
		('SULPHUR DRGS','OTHER',GETDATE()),
		('sulphur drugs','OTHER',GETDATE()),
		('sulphur/ penicilline','OTHER',GETDATE()),
		('swelling of the whole body','Swelling',GETDATE()),
		('ulcers on the skin','Rash',GETDATE())

END