IF OBJECT_ID(N'[ODS].[DBO].[lkp_allergy_causative_agent]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_allergy_causative_agent];
BEGIN
		-- create table statement
		CREATE TABLE [ODS].[DBO].[lkp_allergy_causative_agent](
			source_name VARCHAR(50) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
			target_name VARCHAR(50) NOT NULL,
			date_created DATE NOT NULL
		)

		-- insert table
		INSERT INTO [ODS].[DBO].[lkp_allergy_causative_agent](
				   source_name,
				   target_name,
				   date_created
		)
		VALUES
		('Adhesive Tape','Adhesive tape',GETDATE()),
		('allergic to septrin','Septrin',GETDATE()),
		('allergic to sulphur/ penicilline / ceftriaxone','Sulphur',GETDATE()),
		('Asprin','OTHER',GETDATE()),
		('Bee Stings','Bee Stings',GETDATE()),
		('Beef','Beef',GETDATE()),
		('Beef|Eggs','Beef',GETDATE()),
		('Beef|Eggs|Other','Beef',GETDATE()),
		('Beef|Milk Protein','Beef',GETDATE()),
		('Beef|Milk Protein|Eggs','Beef',GETDATE()),
		('Beef|Other','Beef',GETDATE()),
		('BURNS','OTHER',GETDATE()),
		('Caffeine','Caffeine',GETDATE()),
		('cotrimaxazole','Cotrimaxazole',GETDATE()),
		('COTRIMOXAZOLE','Cotrimaxazole',GETDATE()),
		('CTX','Cotrimaxazole',GETDATE()),
		('Dairy Food','Dairy Food',GETDATE()),
		('Dairy Food|Beef|Milk Protein','Dairy Food',GETDATE()),
		('Dairy Food|Other','Dairy Food',GETDATE()),
		('Dust','Dust',GETDATE()),
		('Dust|Beef|Eggs','Dust',GETDATE()),
		('Dust|Dust','Dust',GETDATE()),
		('Dust|Eggs','Dust',GETDATE()),
		('Dust|Mold','Dust',GETDATE()),
		('Dust|Other','Dust',GETDATE()),
		('Dust|Pollen','Eggs',GETDATE()),
		('Eggs','Eggs',GETDATE()),
		('Eggs|Beef','Eggs',GETDATE()),
		('Eggs|Beef|Milk Protein','Eggs',GETDATE()),
		('Eggs|Milk Protein','Eggs',GETDATE()),
		('Fish','Fish',GETDATE()),
		('Fish|Beef|Eggs','Fish',GETDATE()),
		('Fish|Eggs','Fish',GETDATE()),
		('HIGHLY ALLERGIC TO PENINCILLINS/ SULPHUR','Sulphur',GETDATE()),
		('Latex','Latex',GETDATE()),
		('Milk Protein','Milk protein',GETDATE()),
		('Milk Protein|Beef','Milk protein',GETDATE()),
		('Milk Protein|Beef|Dairy Food','Milk protein',GETDATE()),
		('Milk Protein|Eggs','Milk protein',GETDATE()),
		('Mold','Mould',GETDATE()),
		('NEVIRAPINE','OTHER',GETDATE()),
		('Other','OTHER',GETDATE()),
		('Other|Dust','Dust',GETDATE()),
		('Other|Eggs','Eggs',GETDATE()),
		('Other|Other','OTHER',GETDATE()),
		('Other|Other|Dust','Dust',GETDATE()),
		('Other|Other|Other|Other|Other','OTHER',GETDATE()),
		('Other|Pollen','Pollen',GETDATE()),
		('paracetamol','OTHER',GETDATE()),
		('PARALYISIS','OTHER',GETDATE()),
		('Peanuts','Peanuts',GETDATE()),
		('PENICILLIN','OTHER',GETDATE()),
		('PERIORBITAL OEDEMA','OTHER',GETDATE()),
		('Pollen','Pollen',GETDATE()),
		('Pollen|Dust','Pollen',GETDATE()),
		('Pollen|Other','Pollen',GETDATE()),
		('Pollen|Other|Dust','Pollen',GETDATE()),
		('Pollen|Pollen|Other','Pollen',GETDATE()),
		('rash','OTHER',GETDATE()),
		('rash ,and swelling of the lips','OTHER',GETDATE()),
		('rash after ctx use','OTHER',GETDATE()),
		('RASH AND SORES','OTHER',GETDATE()),
		('RASH AND VOMITING','OTHER',GETDATE()),
		('rashes','OTHER',GETDATE()),
		('SEPRINE','Septrin',GETDATE()),
		('septrin','Septrin',GETDATE()),
		('septrine','Septrin',GETDATE()),
		('Shellfish','Shellfish',GETDATE()),
		('sjs','OTHER',GETDATE()),
		('skin  eruption','OTHER',GETDATE()),
		('skin  rash','OTHER',GETDATE()),
		('skin  rashes','OTHER',GETDATE()),
		('skin eruption','OTHER',GETDATE()),
		('skin rash','OTHER',GETDATE()),
		('skin reaction','OTHER',GETDATE()),
		('Soy','Soy',GETDATE()),
		('steven johnsons sandrome','OTHER',GETDATE()),
		('Strawberries','Strawberries',GETDATE()),
		('SULPHUR','Sulphur',GETDATE()),
		('swelling of the body','OTHER',GETDATE()),
		('Wheat','Wheat',GETDATE())

END