-- FactViralLoad
CREATE TABLE [dbo].FactViralLoad(
	[FactKey] [int] IDENTITY(1,1) NOT NULL,
	[FacilityKey] [int] NULL,
	[PartnerKey] [int] NULL,
	[AgencyKey] [int] NULL,
	[PatientKey] [int] NULL,
	[AgeGroupKey] [int] NULL,
	[PopulationTypeKey] [int] NULL,
	[KeyPopulationTypeKey] [int] NULL,
	[IsEligibleVL] [bit] NULL,
	[Last12MonthVLResults] [varchar] (100) NULL,
	[Last12MonthVL] [bit] NULL,
	[Last12MVLResultCategory] [varchar] (20) NULL,
	[IsLast12MVLSup] [bit] NULL,
	[DateLast12MVLKey] [int] NULL, 
	[Date6MonthVLKey] [int] NULL,
	[6MonthVL] [varchar] (100)  NULL,
	[Date12MonthVLKey] [int] NULL,
	[12MonthVL] [int] NULL,
	[Date18MonthVLKey] [int] NULL,
	[18MonthVL] [int] NULL,
	[Date24MonthVL] [int] NULL,
	[24MonthVL] [int] NULL,
	[Is6MonthVLSup] [bit] NULL,
	[Is12MonthVLSup] [bit] NULL,
	[Is18MonthVLSup] [bit] NULL,
	[Is24MonthVLSup] [bit] NULL,
	[FirstVL] [varchar] (100) NULL,
	[DateFirstVLKey] [int] NULL,
	[LastVL] [varchar] (100) NULL,
	[DateLastVLKey] [int] NULL,
	[TimetoFirstVL] [int] NULL,
	[TimeToFirstVLGroup] [varchar] (50) NULL,
	[DateLastVL1Key] [int] NULL,
	[DateLastVL2Key] [int] NULL,
	[DateLastVL3Key] [int] NULL
)
GO