--FactART
CREATE TABLE [dbo].FactART(
	 [FactKey] [int] IDENTITY(1,1) NOT NULL,
	 [FacilityKey] [int] NULL,
	 [PartnerKey] [int] NULL,
	 [AgencyKey] [int] NULL,
	 [PatientKey] [int] NULL,
	 [AgeGroupKey] [int] NULL,
	 [PopulationTypeKey] [int] NULL,
	 [KeyPopulationTypeKey] [int] NULL,
	 [AgeAtEnroll] [int] NULL,
	 [DateStartARTKey] [int] NULL,
	 [TimetoARTnrollment] [int] NULL,
	 [TimetoARTDiagnosis] [int] NULL,
	 [TimeToARTDiagnosisGroup] [varchar] (50) NULL,
	 [ageARTstart] [int] NULL,
	 [DateLastARTKey] [int] NULL,
	 [CurrentRegimenKey] [int] NULL,
	 [DateLastVisitKey] [int] NULL,
	 [IsOnART<12Months] [bit] NULL,
	 [AgeLastVisit] [int] NULL,
	 [DateNextAppointment] [int] NULL,
	 [IsTXCurr] [bit] NOT NULL,
	 [ARTOutcomeKey] [int] NOT NULL,
	 [StartRegimenKey] [int] NULL,
	 [StartRegimenLineKey] [int] NULL,
	 [CurrentRegimenLineKey] [int] NULL,
	 [AsOfDateKey] [int] NULL,
	 [StartARTAtThisFacility] [bit] NOT NULL,
	 [DatePreviousARTStartKey] [int] NULL,
	 [PreviousARTRegimenKey] [int] NULL,
	 [IsPregnantARTStart] [bit] NULL,
	 [IsPregnantAtEnroll] [bit] NULL,
	 [IsPregnantDuringART] [bit] NULL,
) 
GO