IF OBJECT_ID(N'[ODS].[DBO].[lkp_chronic_illness]', N'U') IS NOT NULL 
	DROP TABLE [ODS].[DBO].[lkp_chronic_illness];
BEGIN
		-- create table statement
		CREATE TABLE [ODS].[DBO].[lkp_chronic_illness](
			source_name VARCHAR(100) NOT NULL PRIMARY KEY WITH (IGNORE_DUP_KEY = ON),
			target_name VARCHAR(100) NOT NULL,
			date_created DATE NOT NULL
		)

		-- insert to table statement
		INSERT INTO [ODS].[DBO].[lkp_chronic_illness](
				   source_name,
				   target_name,
				   date_created
		)
		VALUES
		('Alzheimers Disease and other Dementias','Alzheimer''s Disease and other Dementias',GETDATE()),
		('Arthritis','Arthritis',GETDATE()),
		('Arthritis|Asthma','Arthritis',GETDATE()),
		('Arthritis|Asthma|Hypertension','Arthritis',GETDATE()),
		('Arthritis|Chronic Renal Failure|Osteoporosis','Arthritis',GETDATE()),
		('Arthritis|Diabetes|Hypertension','Arthritis',GETDATE()),
		('Arthritis|Hypertension','Arthritis',GETDATE()),
		('Arthritis|Hypertension|Asthma','Arthritis',GETDATE()),
		('Arthritis|Hypertension|Mental illness','Arthritis',GETDATE()),
		('Arthritis|Hypertension|Obesity','Arthritis',GETDATE()),
		('Arthritis|Obesity','Arthritis',GETDATE()),
		('Arthritis|Osteoporosis','Arthritis',GETDATE()),
		('Asthma','Asthma',GETDATE()),
		('Asthma|Asthma','Asthma',GETDATE()),
		('Asthma|Diabetes','Asthma',GETDATE()),
		('Asthma|Hypertension','Asthma',GETDATE()),
		('Asthma|Hypothyroidism','Asthma',GETDATE()),
		('Asthma|Obesity','Asthma',GETDATE()),
		('Cancer','Cancer',GETDATE()),
		('Cancer|Asthma','Cancer',GETDATE()),
		('Cancer|Chronic Kidney Disease','Cancer',GETDATE()),
		('Cancer|Hypertension','Cancer',GETDATE()),
		('Cancer|Hypertension|Chronic Kidney Disease','Cancer',GETDATE()),
		('Cancer|Mental illness','Cancer',GETDATE()),
		('Cancer|Obesity','Cancer',GETDATE()),
		('Cardiovascular diseases','Cardiovascular diseases',GETDATE()),
		('Cardiovascular diseases|Asthma|Cardiovascular diseases|Asthma','Cardiovascular diseases',GETDATE()),
		('Cardiovascular diseases|Hypertension','Cardiovascular diseases',GETDATE()),
		('Chronic Hepatitis','Chronic Hepatitis',GETDATE()),
		('Chronic Kidney Disease','Chronic Kidney Disease',GETDATE()),
		('Chronic Kidney Disease|Chronic Hepatitis','Chronic Kidney Disease',GETDATE()),
		('Chronic Kidney Disease|Diabetes|Hypertension','Chronic Kidney Disease',GETDATE()),
		('Chronic Kidney Disease|Hypertension','Chronic Kidney Disease',GETDATE()),
		('Chronic Kidney Disease|Thyroid disease','Chronic Kidney Disease',GETDATE()),
		('Chronic Obstructive Pulmonary Disease(COPD)','Chronic Kidney Disease',GETDATE()),
		('Chronic Renal Failure','Chronic Renal Failure',GETDATE()),
		('Chronic Renal Failure|Diabetes|Hypertension','Chronic Renal Failure',GETDATE()),
		('Chronic Renal Failure|Hypertension','Chronic Renal Failure',GETDATE()),
		('Chronic Renal Failure|Hypertension|Diabetes','Chronic Renal Failure',GETDATE()),
		('Chronic Renal Failure|Hypertension|Heart Disease','Chronic Renal Failure',GETDATE()),
		('Cystic Fibrosis','Cystic Fibrosis',GETDATE()),
		('Deafness and Hearing impairment','Deafness and Hearing Impairment',GETDATE()),
		('Deafness and Hearing impairment|Deafness and Hearing impairment','Deafness and Hearing Impairment',GETDATE()),
		('Deafness and Hearing impairment|Hypertension','Deafness and Hearing Impairment',GETDATE()),
		('Diabetes','Diabetes',GETDATE()),
		('Diabetes|Arthritis','Diabetes',GETDATE()),
		('Diabetes|Arthritis|Hypertension','Diabetes',GETDATE()),
		('Diabetes|Asthma','Diabetes',GETDATE()),
		('Diabetes|Asthma|Hypertension','Diabetes',GETDATE()),
		('Diabetes|Cardiovascular diseases','Diabetes',GETDATE()),
		('Diabetes|Chronic Kidney Disease','Diabetes',GETDATE()),
		('Diabetes|Diabetes','Diabetes',GETDATE()),
		('Diabetes|Epilepsy','Diabetes',GETDATE()),
		('Diabetes|Glaucoma','Diabetes',GETDATE()),
		('Diabetes|Heart Disease','Diabetes',GETDATE()),
		('Diabetes|Hyperlipidaemia','Diabetes',GETDATE()),
		('Diabetes|Hypertension','Diabetes',GETDATE()),
		('Diabetes|Hypertension|Arthritis','Diabetes',GETDATE()),
		('Diabetes|Hypertension|Asthma','Diabetes',GETDATE()),
		('Diabetes|Hypertension|Hypertension','Diabetes',GETDATE()),
		('Diabetes|Hypertension|Mental illness','Diabetes',GETDATE()),
		('Diabetes|Hypertension|Obesity','Diabetes',GETDATE()),
		('Diabetes|Hypothyroidism','Diabetes',GETDATE()),
		('Diabetes|Obesity|Hypertension','Diabetes',GETDATE()),
		('Diabetes|Thyroid disease','Diabetes',GETDATE()),
		('Endometriosis','Endometriosis',GETDATE()),
		('Epilepsy','Epilepsy',GETDATE()),
		('Epilepsy|Diabetes','Epilepsy',GETDATE()),
		('Epilepsy|Epilepsy','Epilepsy',GETDATE()),
		('Epilepsy|Hypertension','Epilepsy',GETDATE()),
		('Epilepsy|Hypertension|Diabetes','Epilepsy',GETDATE()),
		('Epilepsy|Mental illness','Epilepsy',GETDATE()),
		('Epilepsy|Obesity','Epilepsy',GETDATE()),
		('Glaucoma','Glaucoma',GETDATE()),
		('Heart Disease','Heart Disease',GETDATE()),
		('Heart Disease|Diabetes|Hypertension','Heart Disease',GETDATE()),
		('Heart Disease|Hypertension','Heart Disease',GETDATE()),
		('Heart Disease|Hypertension|Chronic Kidney Disease','Heart Disease',GETDATE()),
		('Hyperlipidaemia','Hyperlipidaemia',GETDATE()),
		('Hyperlipidaemia|Diabetes|Hypertension','Hyperlipidaemia',GETDATE()),
		('Hyperlipidaemia|Hypertension','Hyperlipidaemia',GETDATE()),
		('Hyperlipidaemia|Obesity','Hypertension',GETDATE()),
		('Hypertension','Hypertension',GETDATE()),
		('Hypertension|Arthritis','Hypertension',GETDATE()),
		('Hypertension|Arthritis|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Asthma','Hypertension',GETDATE()),
		('Hypertension|Asthma|Arthritis','Hypertension',GETDATE()),
		('Hypertension|Asthma|Epilepsy','Hypertension',GETDATE()),
		('Hypertension|Cancer','Hypertension',GETDATE()),
		('Hypertension|Cardiovascular diseases','Hypertension',GETDATE()),
		('Hypertension|Chronic Kidney Disease','Hypertension',GETDATE()),
		('Hypertension|Chronic Kidney Disease|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Chronic Renal Failure','Hypertension',GETDATE()),
		('Hypertension|Deafness and Hearing impairment','Hypertension',GETDATE()),
		('Hypertension|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Diabetes|Chronic Obstructive Pulmonary Disease(COPD)','Hypertension',GETDATE()),
		('Hypertension|Diabetes|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Diabetes|Heart Disease','Hypertension',GETDATE()),
		('Hypertension|Diabetes|Obesity','Hypertension',GETDATE()),
		('Hypertension|Endometriosis','Hypertension',GETDATE()),
		('Hypertension|Epilepsy','Hypertension',GETDATE()),
		('Hypertension|Glaucoma','Hypertension',GETDATE()),
		('Hypertension|Heart Disease','Hypertension',GETDATE()),
		('Hypertension|Hyperlipidaemia','Hypertension',GETDATE()),
		('Hypertension|Hypertension','Hypertension',GETDATE()),
		('Hypertension|Hypertension|Obesity','Hypertension',GETDATE()),
		('Hypertension|Hypothyroidism','Hypertension',GETDATE()),
		('Hypertension|Mental illness','Hypertension',GETDATE()),
		('Hypertension|Mental illness|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Obesity','Hypertension',GETDATE()),
		('Hypertension|Obesity|Diabetes','Hypertension',GETDATE()),
		('Hypertension|Thyroid disease','Hypertension',GETDATE()),
		('Hypothyroidism','Hypothyroidism',GETDATE()),
		('Hypothyroidism|Hypertension','Hypothyroidism',GETDATE()),
		('Hypothyroidism|Hypothyroidism','Hypothyroidism',GETDATE()),
		('Hypothyroidism|Obesity','Hypothyroidism',GETDATE()),
		('Mental illness','Mental illness',GETDATE()),
		('Mental illness|Asthma|Hypertension','Mental illness',GETDATE()),
		('Mental illness|Chronic Kidney Disease','Mental illness',GETDATE()),
		('Mental illness|Chronic Obstructive Pulmonary Disease(COPD)','Mental illness',GETDATE()),
		('Mental illness|Deafness and Hearing impairment','Mental illness',GETDATE()),
		('Mental illness|Hypertension','Mental illness',GETDATE()),
		('Mental illness|Mental illness','Mental illness',GETDATE()),
		('Mental illness|Mental illness|Mental illness','Mental illness',GETDATE()),
		('Mental illness|Multiple Sclerosis','Mental illness',GETDATE()),
		('Multiple Sclerosis','Multiple Sclerosis',GETDATE()),
		('Obesity','Obesity',GETDATE()),
		('Obesity|Asthma','Obesity',GETDATE()),
		('Obesity|Hypertension','Obesity',GETDATE()),
		('Obesity|Hypothyroidism','Obesity',GETDATE()),
		('Obesity|Obesity','Obesity',GETDATE()),
		('Obesity|Obesity|Diabetes','Obesity',GETDATE()),
		('Osteoporosis','Osteoporosis',GETDATE()),
		('Sickle Cell Anaemia','Sickle Cell Anaemia',GETDATE()),
		('Thyroid disease','Thyroid disease',GETDATE()),
		('Thyroid disease|Chronic Kidney Disease','Thyroid disease',GETDATE()),
		('Thyroid disease|Diabetes','Thyroid disease',GETDATE()),
		('Thyroid disease|Hypertension','Thyroid disease',GETDATE()),
		('Thyroid disease|Hypertension|Obesity','Thyroid disease',GETDATE()),
		('Thyroid disease|Thyroid disease','Thyroid disease',GETDATE())

END