SELECT --[PatientID]
      --,[Patientpk]
      [SiteCode]
      ,[AdverseEvent]
      ,[AdverseEventStartDate]
      ,[AdverseEventEndDate]
      ,[Severity]
      ,[VisitDate]
      ,[EMR]
      ,[Project]
      ,[AdverseEventCause]
      ,[AdverseEventRegimen]
      ,[AdverseEventActionTaken]
      ,[AdverseEventClinicalOutcome]
      ,[AdverseEventIsPregnant]
      ,[FacilityName]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_AdverseEvents]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;
