SELECT  [SiteCode]
      --,[PatientPK]
      ,[Emr]
      ,[Project]
      ,[Voided]
      ,[Id]
      ,[FacilityName]
      ,[ARTRefillModel]
      ,[VisitDate]
      ,[CTXDispensed]
      ,[DapsoneDispensed]
      ,[CondomsDistributed]
      ,[OralContraceptivesDispensed]
      ,[MissedDoses]
      ,[Fatigue]
      ,[Cough]
      ,[Fever]
      ,[Rash]
      ,[NauseaOrVomiting]
      ,[GenitalSoreOrDischarge]
      ,[Diarrhea]
      ,[OtherSymptoms]
      ,[PregnancyStatus]
      ,[FPStatus]
      ,[FPMethod]
      ,[ReasonNotOnFP]
      ,[ReferredToClinic]
      ,[ReturnVisitDate]
      ,[RecordUUID]
      ,[Date_Created]
      ,[Date_Last_Modified]
      ,[Created]
      --,[PatientId]
      ,[LoadDate]
      ,[PatientPKHash]
      ,[PatientIDHash]
  FROM [ODS].[dbo].[CT_ArtFastTrack]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;