SELECT [AllergiesChronicIllnessUnique_ID]
      --,[PatientID]
      --,[PatientPK]
      ,[FacilityID]
      ,[SiteCode]
      ,[FacilityName]
      ,[SatelliteName]
      ,[VisitID]
      ,[VisitDate]
      ,[Emr]
      ,[Project]
      ,[ChronicIllness]
      ,[ChronicOnsetDate]
      ,[knownAllergies]
      ,[AllergyCausativeAgent]
      ,[AllergicReaction]
      ,[AllergySeverity]
      ,[AllergyOnsetDate]
      ,[Skin]
      ,[Eyes]
      ,[ENT]
      ,[Chest]
      ,[CVS]
      ,[Abdomen]
      ,[CNS]
      ,[Genitourinary]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
      ,[Controlled]
  FROM [ODS].[dbo].[CT_AllergiesChronicIllness]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;