SELECT 
--[PatientID]
--      ,[PatientPK]
      [SiteCode]
      ,[FacilityName]
      ,[Emr]
      ,[Project]
      --,[PartnerPersonID]
      ,[ContactAge]
      ,[ContactSex]
      ,[ContactMaritalStatus]
      ,[RelationshipWithPatient]
      ,[ScreenedForIpv]
      ,[IpvScreening]
      ,[IPVScreeningOutcome]
      ,[CurrentlyLivingWithIndexClient]
      ,[KnowledgeOfHivStatus]
      ,[PnsApproach]
      --,[ContactPatientPK]
      ,[DateCreated]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ContactPatientPKHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_ContactListing]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;