SELECT [SiteCode]
      --,[PatientPK]
      --,[PatientID]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[Emr]
      ,[Project]
      ,[Voided]
      ,[Processed]
      ,[Id]
      ,[FacilityName]
      ,[VisitID]
      ,[VisitDate]
      ,[VisitType]
      ,[ScreeningMethod]
      ,[TreatmentToday]
      ,[ReferredOut]
      ,[NextAppointmentDate]
      ,[ScreeningType]
      ,[ScreeningResult]
      ,[PostTreatmentComplicationCause]
      ,[OtherPostTreatmentComplication]
      ,[ReferralReason]
      ,[Created]
      ,[Date_Created]
      ,[Date_Last_Modified]
      ,[LoadDate]
      ,[RecordUUID]
  FROM [ODS].[dbo].[CT_CervicalCancerScreening]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [Voided] = 0;