SELECT 
--[PatientID]
--      ,[PatientPK]
      [SiteCode]
      ,[FacilityName]
      ,[VisitID]
      ,[VisitDate]
      ,[Emr]
      ,[Project]
      ,[PHQ9_1]
      ,[PHQ9_2]
      ,[PHQ9_3]
      ,[PHQ9_4]
      ,[PHQ9_5]
      ,[PHQ9_6]
      ,[PHQ9_7]
      ,[PHQ9_8]
      ,[PHQ9_9]
      ,[PHQ_9_rating]
      ,[DepressionAssesmentScore]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_DepressionScreening]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;