SELECT [Voided]
      ,[Processed]
      ,[SiteCode]
      ,[PatientCount]
      ,[DateRecieved]
      ,[Name]
      ,[EmrName]
      ,[EmrSetup]
      ,[UploadMode]
      ,[Start]
      ,[End]
      ,[Tag]
      ,[CreatedOn]
      ,[PatientPKHash]
      ,[CKVHash]
      ,[PatientIDHash]
      ,[ID]
  FROM [ODS].[dbo].[CT_FacilityManifest]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [Voided] = 0;