SELECT 
--[PatientID]
--      ,[PatientPK]
      [FacilityID]
      ,[SiteCode]
      ,[FacilityName]
      ,[SatelliteName]
      ,[VisitID]
      ,[VisitDate]
      ,[Emr]
      ,[Project]
      ,[IPV]
      ,[PhysicalIPV]
      ,[EmotionalIPV]
      ,[SexualIPV]
      ,[IPVRelationship]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_GbvScreening]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;