SELECT TOP (1000) [SiteCode]
      --,[PatientID]
      --,[PatientPK]
      [PatientPKHash]
      ,[PatientIDHash]
      ,[Emr]
      ,[Project]
      ,[Voided]
      ,[Processed]
      ,[Id]
      ,[FacilityName]
      ,[SourceSysUUID]
      ,[RiskScore]
      ,[RiskFactors]
      ,[RiskDescription]
      ,[RiskEvaluationDate]
      ,[Created]
      ,[Date_Created]
      ,[Date_Last_Modified]
      ,[LoadDate]
  FROM [ODS].[dbo].[CT_IITRiskScores]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [Voided] = 0;