SELECT
--[PatientID]
--      ,[PatientPK]
      [FacilityID]
      ,[SiteCode]
      ,[FacilityName]
      ,[SatelliteName]
      ,[VisitID]
      ,[VisitDate]
      ,[Emr]
      ,[Project]
      ,[OTZEnrollmentDate]
      ,[TransferInStatus]
      ,[ModulesPreviouslyCovered]
      ,[ModulesCompletedToday]
      ,[SupportGroupInvolvement]
      ,[Remarks]
      ,[TransitionAttritionReason]
      ,[OutcomeDate]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_Otz]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;