SELECT 
--[PatientID]
--      ,[PatientPK]
      [FacilityID]
      ,[SiteCode]
      ,[FacilityName]
      ,[SatelliteName]
      ,[VisitID]
      ,[VisitDate]
      ,[Emr]
      ,[Project]
      ,[OVCEnrollmentDate]
      ,[RelationshipToClient]
      ,[EnrolledinCPIMS]
      ,[CPIMSUniqueIdentifier]
      ,[PartnerOfferingOVCServices]
      ,[OVCExitReason]
      ,[ExitDate]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[CPIMSUniqueIdentifierHash]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_Ovc]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;