SELECT 
--[PatientID]
      [SiteCode]
      ,[FacilityName]
      ,[ExitDescription]
      ,[ExitDate]
      ,[ExitReason]
      --,[PatientPK]
      ,[Emr]
      ,[Project]
      ,[DateImported]
      ,[TOVerified]
      ,[TOVerifiedDate]
      ,[ReEnrollmentDate]
      ,[ReasonForDeath]
      ,[SpecificDeathReason]
      ,[DeathDate]
      ,[EffectiveDiscontinuationDate]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_PatientStatus]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;