SELECT 
--[PatientID]
--      ,[PatientPk]
      [FacilityID]
      ,[SiteCode]
      ,[FacilityName]
      ,[SatelliteName]
      ,[VisitID]
      ,[OrderedbyDate]
      ,[ReportedbyDate]
      ,[TestName]
      ,[EnrollmentTest]
      ,[TestResult]
      ,[BaselineTest]
      ,[Emr]
      ,[Project]
      ,[DateSampleTaken]
      ,[SampleType]
      ,[Processed]
      ,[Created]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[ID]
      ,[Reason]
      ,[Date_Last_Modified]
      ,[Date_Created]
      ,[LoadDate]
      ,[RecordUUID]
      ,[voided]
  FROM [ODS].[dbo].[CT_PatientLabs]
  WHERE  [PatientIDHash] IS NULL OR [PatientPKHash] IS NULL AND [voided] = 0;