SELECT [SiteCode]
      --,[PatientPK]
      --,[PatientID]
      ,[Emr]
      ,[Project]
      ,[Voided]
      ,[Id]
      ,[FacilityName]
      ,[RelationshipToPatient]
      ,[StartDate]
      ,[EndDate]
      ,[RecordUUID]
      ,[Date_Created]
      ,[Date_Last_Modified]
      ,[Created]
      ,[LoadDate]
      ,[PatientPKHash]
      ,[PatientIDHash]
      ,[PersonAPatientPk]
      ,[PersonBPatientPk]
      ,[PatientRelationshipToOther]
      ,[PersonAPatientPkHash]
      ,[PersonBPatientPkHash]
  FROM [ODS].[dbo].[CT_Relationships]
  WHERE [PatientPKHash] IS NULL OR [PatientIDHash] IS NULL;
